name: Tester Next.js

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            # Recomenda-se usar uma imagem baseada em Node.js se estiver usando 'container'
            # (Você já está fazendo isso corretamente, o que define o ambiente básico)
            image: node:20 
        steps:
            # 1. Checkout do Código (sem parâmetro node-version)
            - uses: actions/checkout@v4 # Atualizado para v4 ou v5 (opcional, mas recomendado)
              with:
                  fetch-depth: 20
            # 3. Executar Comandos
            - run: npm ci
            - run: npm test
            - run: npm run build